
name: 'sumup'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +incremental_strategy: "append"
  sumup:
    staging:
      schema: stg
      +tags: stg
    core:
      schema: core
      +tags: core
    marts:
      schema: mart
      +tags: mart
    intermediate:
      schema: intermediate
      +tags: intermediate

seeds:
  sumup:
    +schema: seeds
